export enum ROUTE {
  HOME = '/',
  PROFILE = '/profile',
  PLATFORMS = '/platforms',
  PLATFORMS_DETAILS = '/platforms/:platformId',
  SIGN_UP = '/sign-up',
  SIGN_IN = '/sign-in',
  RESET_PASSWORD = '/reset-password',
  NEW_PASSWORD = '/new-password',
  PROFILE_SETTINGS = 'settings',
  PROFILE_FAVORITES = 'favorites',
  PROFILE_FAVORITES_PLATFORMS = 'platforms',
  PROFILE_FAVORITES_SOLUTIONS = 'solutions',
  PROFILE_HISTORY = 'history',
  ADMIN = '/admin',
}
